# Generated by Django 5.2.7 on 2025-10-30 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shootingschedule',
            name='actors',
        ),
        migrations.AlterField(
            model_name='shootingschedule',
            name='status',
            field=models.CharField(choices=[('available', 'Tersedia'), ('closed', 'Ditutup'), ('completed', 'Selesai')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='ScheduleApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('confirmed', 'Terkonfirmasi'), ('rejected', 'Ditolak')], default='pending', max_length=16)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='schedule.shootingschedule')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('schedule', 'actor')},
            },
        ),
    ]
